---
- name: Updates apt repositories
  ansible.builtin.apt:
    update_cache: true
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    install_recommends: false
    state: present

- name: Adding Docker repository to apt
  block:
    - name: Get key for Docker repo
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /tmp/docker.asc
        mode: "0660"

    - name: Add apt repository
      ansible.builtin.apt_repository:
        repo: deb [arch=$(dpkg --print-architecture) signed-by=/tmp/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
        state: present

- name: Install docker
  ansible.builtin.apt:
    update_cache: true
    name:
      - docker-ce
    install_recommends: false
    state: present
